In [1]:
import numpy as np
li_arr = [i for i in range(0,100)]
np_arr = np.arange(100)

print(li_arr)


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]


In [2]:
print(np_arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [3]:
print((np_arr.itemsize))

8


In [4]:
print(np_arr.itemsize * np_arr.size)

800


In [5]:
print(np_arr.size)

100


In [6]:
import sys
a = 10
print(sys.getsizeof(a))
print(sys.getsizeof(1) * len(li_arr))

28
2800


In [7]:
import time
import numpy as np

size = 100000


def addition_using_list():
    t1 = time.time()
    a = range(size)
    b = range(size)
    c = [a[i] + b[i] for i in range(size)]
    t2 = time.time()
    return  (t2 -t1)


def addition_using_numpy():
    t1 = time.time()
    a = np.arange(size)
    b = np.arange(size)
    c = a + b
    t2 = time.time()
    return  (t2 - t1)

t_list = addition_using_list()
t_numpy = addition_using_numpy()
print('list = ',t_list * 100)
print('numpy = ',t_numpy * 100)


list =  2.1372079849243164
numpy =  0.13167858123779297


# Boolean indexing_1D

In [10]:
import numpy as np

a = np.array (['t','r','b','d','e','f','z','a'])
b = np.random.randint(1,20,8)

print(a)
print(b)
print(type(a))
print(type(b))

['t' 'r' 'b' 'd' 'e' 'f' 'z' 'a']
[ 7  1 11 17 11  9  8 12]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [11]:
print(b>10)

[False False  True  True  True False False  True]


In [12]:
print(b<10)

[ True  True False False False  True  True False]


In [13]:
print((type(a)))

<class 'numpy.ndarray'>


In [14]:
bool_arr = b > 10
print(bool_arr)
new_arr = b[bool_arr]
print(new_arr)

[False False  True  True  True False False  True]
[11 17 11 12]


In [15]:
new_arr = b[bool_arr]
print(new_arr)

[11 17 11 12]


In [16]:
new_arr = b[(b>10) & (b>18)]
new_arr

array([], dtype=int64)

In [17]:
print(b)
c = b
c

[ 7  1 11 17 11  9  8 12]


array([ 7,  1, 11, 17, 11,  9,  8, 12])

In [18]:
c[:3] = 19
print(c)
c[c>15] = 100
c

[19 19 19 17 11  9  8 12]


array([100, 100, 100, 100,  11,   9,   8,  12])

In [19]:
print(b[b == 100])

[100 100 100 100]


In [20]:
ind = np.where(b == 100)
ind

(array([0, 1, 2, 3]),)

In [21]:
print(a)
print(b)

['t' 'r' 'b' 'd' 'e' 'f' 'z' 'a']
[100 100 100 100  11   9   8  12]


In [22]:
import numpy as np
arr = np.array([1,2,0,0,4,0])
ind = np.where(arr != 0)
print(*ind)

[0 1 4]


In [23]:
import numpy as np
arr = np.array([1,  3,  5,  7,  9, 11, 13, 15, 17, 19])
ind = np.where(arr%3 == 0)
print(*ind[0])

1 4 7


In [24]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
arr[arr %2 != 0] = -1
print(*arr)

-1 2 -1 4 -1 6 -1 8 -1 10


In [25]:
import numpy as np
arr = np.array([11, 2, 13, 4, 15, 6, 27, 8, 19])
arr[arr.argmax()] = 0
for i in arr :
    
    print(i)

11
2
13
4
15
6
0
8
19


# Boolean indexing_2D

In [26]:
import numpy as np
a = np.random.randint(1,30,(5,6))
print(arr)

[11  2 13  4 15  6  0  8 19]


In [27]:
print(a>10)

[[False False False False False  True]
 [ True False False  True  True  True]
 [ True False  True  True  True  True]
 [ True  True False False False False]
 [False  True  True  True False False]]


In [28]:
a>20

array([[False, False, False, False, False,  True],
       [ True, False, False, False, False,  True],
       [ True, False,  True, False,  True,  True],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [29]:
a<12

array([[ True,  True,  True,  True,  True, False],
       [False,  True,  True, False, False, False],
       [False,  True, False, False, False, False],
       [ True,  True,  True,  True,  True,  True],
       [ True, False, False, False,  True,  True]])

In [30]:
bool_arr = a > 20
bool_arr

array([[False, False, False, False, False,  True],
       [ True, False, False, False, False,  True],
       [ True, False,  True, False,  True,  True],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [31]:
ans = a[bool_arr]
ans

array([29, 24, 26, 23, 27, 25, 28])

In [33]:
b = a

In [34]:
print(a)

[[10  3 10  3  9 29]
 [24  7  7 12 16 26]
 [23  1 27 13 25 28]
 [11 11  7 10  2  1]
 [ 7 18 12 15  5  4]]


In [35]:
b[bool_arr] = 100
print(b)

[[ 10   3  10   3   9 100]
 [100   7   7  12  16 100]
 [100   1 100  13 100 100]
 [ 11  11   7  10   2   1]
 [  7  18  12  15   5   4]]


In [36]:
c = np.random.randint(1,10,(2,2))
print(c)

[[3 7]
 [9 4]]


In [37]:
c_bool = np.array([[True, False],[False,True]])
c_bool

array([[ True, False],
       [False,  True]])

In [38]:
print(b)

[[ 10   3  10   3   9 100]
 [100   7   7  12  16 100]
 [100   1 100  13 100 100]
 [ 11  11   7  10   2   1]
 [  7  18  12  15   5   4]]


In [39]:
bool_arr = b[:,3] == 100
print(bool_arr)

[False False False False False]


In [40]:
b[bool_arr, 3] = 15
print(b)

[[ 10   3  10   3   9 100]
 [100   7   7  12  16 100]
 [100   1 100  13 100 100]
 [ 11  11   7  10   2   1]
 [  7  18  12  15   5   4]]


In [41]:
b[bool_arr,4] = 3
print(b)

[[ 10   3  10   3   9 100]
 [100   7   7  12  16 100]
 [100   1 100  13 100 100]
 [ 11  11   7  10   2   1]
 [  7  18  12  15   5   4]]


In [43]:
b[bool_arr,0] = 19
print(b)

[[ 10   3  10   3   9 100]
 [100   7   7  12  16 100]
 [100   1 100  13 100 100]
 [ 11  11   7  10   2   1]
 [  7  18  12  15   5   4]]


# create Array list

In [46]:
import numpy as np

a = [1,2,3,4]
b = np.array(a)
print(b)
print(type(b))

[1 2 3 4]
<class 'numpy.ndarray'>


In [47]:
print(type(a))

<class 'list'>


In [48]:
import numpy as np

a = [1,2,3,4, '5', '10']
b = np.array(a,dtype = float)
print(b)

[ 1.  2.  3.  4.  5. 10.]


In [49]:
print(type(b))

<class 'numpy.ndarray'>


In [50]:
b = np.array(a,dtype = int)
print(b)

[ 1  2  3  4  5 10]


In [51]:
b = np.array(a,dtype = str)
print(b)

['1' '2' '3' '4' '5' '10']


In [52]:
b = np.array(a * 5)
print(b)

['1' '2' '3' '4' '5' '10' '1' '2' '3' '4' '5' '10' '1' '2' '3' '4' '5'
 '10' '1' '2' '3' '4' '5' '10' '1' '2' '3' '4' '5' '10']


In [53]:
b = np.ones(3,dtype = int)
b

array([1, 1, 1])

In [54]:
b = np.ones((2,3),dtype = int)
b

array([[1, 1, 1],
       [1, 1, 1]])

In [55]:
b = np.zeros(3,dtype = int)
print(b)

[0 0 0]


In [56]:
b = np.zeros((4,3),dtype = int)
print(b)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [57]:
b = np.zeros((4,3))
print(b)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [58]:
b = np.full(3,5)
b

array([5, 5, 5])

In [59]:
import numpy as np
list_int = [0,0,0,0,0,1,0,0,0,0]

print(list_int)

[0, 0, 0, 0, 0, 1, 0, 0, 0, 0]


In [60]:
b = np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
b = np.arange(2,10)
b

array([2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
b = np.arange(2,10,2)
b

array([2, 4, 6, 8])

In [63]:
b = np.arange(3,33,3)
b

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [64]:
b = np.linspace(2, 10)
b
print(b[1] - b[0])

0.16326530612244916


In [65]:
b = np.linspace(2,10,5, dtype = int, endpoint = False)
print(b)

[2 3 5 6 8]


In [66]:
b = np.identity(5)
(b)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [67]:
b = np.eye(5,4)
b

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [68]:
b = np.random.rand()
b

0.3668557959258625

In [69]:
b = np.random.rand()
b

0.5020093276176266

In [70]:
b = np.random.rand(4) * 4
b

array([1.98099666, 2.02083282, 0.56123045, 2.71245139])

In [72]:
b = np.arange(10)

In [73]:
a = np.arange(9,50)
print(*a)

9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49


In [74]:
import numpy as np
a = np.eye(5,6)
print(a) 

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]]


In [75]:
b = np.identity(5)
(b)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [76]:
import numpy as np
a = np.eye(6,5,dtype = int)
print(a)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]
 [0 0 0 0 0]]


In [77]:
import numpy as np
arr = np.linspace(0,5,10)
print(*arr)
for i in range(1, len(arr)-1) :
    print(round(arr[i],2))

0.0 0.5555555555555556 1.1111111111111112 1.6666666666666667 2.2222222222222223 2.7777777777777777 3.3333333333333335 3.8888888888888893 4.444444444444445 5.0
0.56
1.11
1.67
2.22
2.78
3.33
3.89
4.44


# some mathematical terms

In [78]:
import numpy as np
li = [1, 2, 3, 4, 5]
a = np.random.randint(1, 20, 5)
b = np.random.randint(1, 20, 5)

print(li)
print(a)
print(b)

[1, 2, 3, 4, 5]
[15 11 13 10  8]
[ 9 17  4 10 12]


In [79]:
a = 1 + 1
a

2

In [80]:
c = a+b
c

array([11, 19,  6, 12, 14])

In [81]:
d = a - b
d

array([ -7, -15,  -2,  -8, -10])

In [82]:
e = a * b
e

array([18, 34,  8, 20, 24])

In [83]:
f = a / b
f

array([0.22222222, 0.11764706, 0.5       , 0.2       , 0.16666667])

In [84]:
g = a % b
g

array([2, 2, 2, 2, 2])

In [85]:
h = a //b
h

array([0, 0, 0, 0, 0])

In [86]:
i = a**b
i

array([   512, 131072,     16,   1024,   4096])

In [89]:
a = np.array([1, 2, 3, 4, 5])
print(a.sum())
print(a.mean())


15
3.0


In [90]:
print(a)
print(b)

[1 2 3 4 5]
[ 9 17  4 10 12]


In [91]:
a>b

array([False, False, False, False, False])

In [92]:
a<b

array([ True,  True,  True,  True,  True])

In [93]:
a==b

array([False, False, False, False, False])

In [94]:
print(np.logical_or(a,b))
print(np.logical_and(a,b))
print(np.logical_not(a,b))

[ True  True  True  True  True]
[ True  True  True  True  True]
[0 0 0 0 0]


In [95]:
a[2] = 0
print(a)
print(np.logical_not(a,b))

[1 2 0 4 5]
[0 0 1 0 0]


# numpy_BroadCasting

In [97]:
x = np.random.randint(1,5, (3,2))
y = np.random.randint(1,5, (3,2))
print(x)
print(y)

[[1 4]
 [3 4]
 [3 1]]
[[3 1]
 [1 1]
 [1 1]]


In [98]:
a = x - y
print(a)

[[-2  3]
 [ 2  3]
 [ 2  0]]


In [99]:
a = x + y
print(a)

[[4 5]
 [4 5]
 [4 2]]


In [100]:
a = x * y
a

array([[3, 4],
       [3, 4],
       [3, 1]])

In [101]:
a = x / y
a

array([[0.33333333, 4.        ],
       [3.        , 4.        ],
       [3.        , 1.        ]])

In [102]:
a = x == y
a

array([[False, False],
       [False, False],
       [False,  True]])

In [103]:
a = x % y == 0
a

array([[False,  True],
       [ True,  True],
       [ True,  True]])

In [104]:
a = x**y
a

array([[1, 4],
       [3, 4],
       [3, 1]])